[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
runner = [
    "C:\\Program Files\\qemu\\qemu-system-riscv64.exe",
    "-machine", "virt",
    "-display", "gtk",
    "-serial", "stdio",
    "-device", "virtio-gpu-device,bus=virtio-mmio-bus.0,xres=800,yres=480",
    "-D", "qemu.log",
    "-bios", "none",
    "-kernel",
]

[env]
TG_USER_CRATE = "tg-rcore-tutorial-user"
TG_USER_LOCAL_DIR = "../tg-rcore-tutorial-user"
TG_USER_VERSION = "0.4.10"
